server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "chlen12"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
    bufferDurationMs: 400
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
